"""Read-only local dashboard for RAG failure patterns and correction SOP.

The page reads one aggregate-only JSON artifact generated by
``scripts/analyze_rag_failures.py``.  It never opens a private answer key,
holdout input, photo, vector, trace, or network connection, and it cannot
apply the proposed correction automatically.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import streamlit as st
from streamlit.components.v1 import html as render_component

from portrait_consistency_agent.services.rag_report_registry import (
    RAG_REPORT_ARTIFACTS,
    read_rag_report,
)

PROJECT_ROOT = Path(__file__).resolve().parents[1]


def _load_json_report() -> dict[str, Any] | None:
    path = PROJECT_ROOT / "reports/rag_failure_patterns_v1.json"
    if not path.is_file():
        return None
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None
    return value if isinstance(value, dict) else None


def _load_optimization_report() -> dict[str, Any] | None:
    path = PROJECT_ROOT / "reports/rag_optimization_loop_v1.json"
    if not path.is_file():
        return None
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None
    return value if isinstance(value, dict) else None


def _load_failure_driven_report() -> dict[str, Any] | None:
    path = PROJECT_ROOT / "reports/rag_failure_driven_loop_v1.json"
    if not path.is_file():
        return None
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None
    return value if isinstance(value, dict) else None


def _percent(value: object) -> str:
    if isinstance(value, (int, float)):
        return f"{float(value) * 100:.2f}%"
    return "—" if value is None else str(value)


def _metric_value(metrics: dict[str, Any], name: str) -> str:
    return _percent(metrics.get(name))


def _split_rows(groups: object) -> list[dict[str, object]]:
    if not isinstance(groups, dict):
        return []
    rows: list[dict[str, object]] = []
    for name, value in groups.items():
        if not isinstance(value, dict) or not str(name).startswith("split:"):
            continue
        rows.append(
            {
                "分组": str(name).removeprefix("split:"),
                "题数": value.get("cases", 0),
                "路由正确率": _percent(value.get("route_accuracy")),
                "关系正确率": _percent(value.get("evidence_relation_accuracy")),
                "固定 Precision@3": _percent(value.get("fixed_precision_at_3_mean")),
                "按返回条数诊断值": _percent(value.get("precision_at_returned_mean_diagnostic")),
            }
        )
    return rows


def _pattern_rows(patterns: object) -> list[dict[str, object]]:
    if not isinstance(patterns, list):
        return []
    return [
        {
            "模式": item.get("pattern_id", ""),
            "严重度": item.get("severity", ""),
            "证据级别": item.get("evidence_level", ""),
            "诊断": item.get("diagnosis", ""),
            "建议修正": item.get("correction", ""),
        }
        for item in patterns
        if isinstance(item, dict)
    ]


def _sop_rows(sop: object) -> list[dict[str, object]]:
    if not isinstance(sop, list):
        return []
    return [
        {
            "步骤": item.get("step", ""),
            "名称": item.get("name", ""),
            "执行": item.get("action", ""),
            "禁止": item.get("must_not", ""),
        }
        for item in sop
        if isinstance(item, dict)
    ]


def main() -> None:
    st.set_page_config(page_title="RAG 优化看板｜母版人像一致性 Agent", page_icon="🧪")
    report = _load_json_report()
    optimization = _load_optimization_report()
    failure_driven = _load_failure_driven_report()
    st.title("RAG 优化看板（本地管理员原型）")
    st.caption(
        "这张看板把公开集事实、隐藏集聚合错误和下一步修正 SOP 放在一起，帮助定位问题，"
        "但不会自动修改检索器、权限或 Provider。"
    )
    st.warning(
        "当前 RAG baseline 尚未通过项目 Gate。隐藏集只回流聚合统计；本页不读隐藏答案键、"
        "不展示隐藏题干/编号，也不把聚合结果当作逐题调参标签。"
    )
    if failure_driven is not None:
        st.subheader("失败驱动迭代（查询理解层）")
        st.caption(
            "上一轮候选只改了已经生成的 Prediction；这一轮把修正放到"
            "‘自然语言→结构化 RAG 查询’之前。"
            "开发集标记为 owner_review_required，未替代正式 baseline。"
        )
        generations = failure_driven.get("generations", [])
        generations = generations if isinstance(generations, list) else []
        table: list[dict[str, object]] = []
        chart: list[dict[str, object]] = []
        for generation in generations:
            if not isinstance(generation, dict):
                continue
            metrics = generation.get("metrics", {})
            metrics = metrics if isinstance(metrics, dict) else {}
            table.append(
                {
                    "代次": generation.get("generation_id", "—"),
                    "候选": generation.get("version", "—"),
                    "实际改变预测数": generation.get("changed_prediction_count", "—"),
                    "Composite": generation.get("composite_score", "—"),
                    "增益": generation.get("composite_gain_vs_previous", "—"),
                    "Route": _percent(metrics.get("route_accuracy")),
                    "Relation": _percent(metrics.get("evidence_relation_accuracy")),
                    "Recall@5": _percent(metrics.get("recall_at_5")),
                    "公开回归 Gate": generation.get("regression_gate", "—"),
                }
            )
            if isinstance(generation.get("composite_score"), (int, float)):
                chart.append(
                    {
                        "代次": str(generation.get("generation_id", "—")),
                        "Composite": float(generation["composite_score"]),
                    }
                )
        st.dataframe(table, use_container_width=True, hide_index=True)
        if chart:
            st.line_chart(chart, x="代次", y="Composite")
        pattern_block = failure_driven.get("failure_patterns", {})
        pattern_block = pattern_block if isinstance(pattern_block, dict) else {}
        st.write("V0 失败模式：", pattern_block.get("baseline_failure_code_counts", {}))
        st.write("停止原因：", failure_driven.get("stop_reason", "—"))
        baseline_block = failure_driven.get("baseline", {})
        baseline_block = baseline_block if isinstance(baseline_block, dict) else {}
        failure_case_rows = baseline_block.get("case_diagnostics", [])
        failure_case_rows = failure_case_rows if isinstance(failure_case_rows, list) else []
        with st.expander("查看失败驱动集逐题结论（不含 v3 私有答案）"):
            st.caption("表格只显示本轮 owner-review 开发/挑战集的 case ID、标签和结构化错误码。")
            st.dataframe(failure_case_rows, use_container_width=True, hide_index=True)
        st.write(
            "当前结论：",
            "查询编译候选在新开发集有明显增益；仍需产品负责人审核该数据集，"
            "并用独立 Holdout v4 验收。",
        )
        failure_artifact = next(
            (item for item in RAG_REPORT_ARTIFACTS if item.key == "failure_driven_loop"), None
        )
        if failure_artifact is not None:
            failure_path = failure_artifact.path(PROJECT_ROOT)
            if failure_path.is_file():
                st.download_button(
                    "下载失败驱动优化 HTML",
                    data=failure_path.read_bytes(),
                    file_name=failure_path.name,
                    mime="text/html",
                )
                render_component(
                    read_rag_report(failure_artifact, PROJECT_ROOT),
                    height=680,
                    scrolling=True,
                )
    if optimization is not None:
        st.subheader("版本化自动优化迭代")
        st.caption(
            "逐代只改一个可解释候选；Composite 仅作比较分，不能覆盖固定项目 Gate 或 hard-safety。"
        )
        generations = optimization.get("generations", [])
        generations = generations if isinstance(generations, list) else []
        generation_table: list[dict[str, object]] = []
        chart_rows: list[dict[str, object]] = []
        for generation in generations:
            if not isinstance(generation, dict):
                continue
            metrics = generation.get("metrics", {})
            metrics = metrics if isinstance(metrics, dict) else {}
            generation_table.append(
                {
                    "代次": generation.get("generation_id", "—"),
                    "候选版本": generation.get("version", "—"),
                    "状态": generation.get("status", "—"),
                    "Composite": generation.get("composite_score", "—"),
                    "增益": generation.get("composite_gain_vs_previous", "—"),
                    "Route": _percent(metrics.get("route_accuracy")),
                    "Recall@5": _percent(metrics.get("recall_at_5")),
                    "Project Gate": generation.get("project_threshold_gate", "—"),
                }
            )
            if isinstance(generation.get("composite_score"), (int, float)):
                chart_rows.append(
                    {
                        "代次": str(generation.get("generation_id", "—")),
                        "Composite": float(generation["composite_score"]),
                    }
                )
        st.dataframe(generation_table, use_container_width=True, hide_index=True)
        if chart_rows:
            st.line_chart(chart_rows, x="代次", y="Composite")
        anti_overfit = optimization.get("anti_overfit", {})
        anti_overfit = anti_overfit if isinstance(anti_overfit, dict) else {}
        status_cols = st.columns(3)
        executed_label = " → ".join(str(x) for x in optimization.get("executed_generations", []))
        status_cols[0].metric("执行代次", executed_label)
        status_cols[1].metric("反过拟合", anti_overfit.get("status", "—"))
        stop_label = (
            "边际效益递减" if "diminishing" in str(optimization.get("stop_reason")) else "计划完成"
        )
        status_cols[2].metric("停止原因", stop_label)
        public_patterns = optimization.get("failure_patterns", {})
        public_patterns = public_patterns if isinstance(public_patterns, dict) else {}
        case_diagnostics = optimization.get("baseline", {})
        case_diagnostics = case_diagnostics if isinstance(case_diagnostics, dict) else {}
        case_rows = case_diagnostics.get("case_diagnostics", [])
        case_rows = case_rows if isinstance(case_rows, list) else []
        st.write("公开集逐题模式计数：", public_patterns.get("public_case_pattern_counts", {}))
        with st.expander("查看公开集逐题诊断（不含原始题干）"):
            st.dataframe(case_rows, use_container_width=True, hide_index=True)
        interpretations = public_patterns.get("private_pattern_interpretations", [])
        if isinstance(interpretations, list) and interpretations:
            st.subheader("v3 聚合模式：事实与假设分开")
            interpretation_rows = []
            for item in interpretations:
                if not isinstance(item, dict):
                    continue
                causes = item.get("plausible_causes", [])
                if not isinstance(causes, list):
                    causes = []
                interpretation_rows.append(
                    {
                        "模式": item.get("pattern_id", "—"),
                        "计数": item.get("count", 0),
                        "证据级别": item.get("evidence_level", "—"),
                        "观察事实": item.get("what_is_observed", "—"),
                        "可验证假设": "；".join(str(cause) for cause in causes),
                        "下一份 Holdout 要补的证据": item.get("next_evidence_needed", "—"),
                    }
                )
            st.dataframe(interpretation_rows, use_container_width=True, hide_index=True)
            st.caption("v3 模式计数可能重叠；假设不等于隐藏集逐题答案，需在独立 Holdout v4 验证。")
        optimization_artifact = next(
            (item for item in RAG_REPORT_ARTIFACTS if item.key == "optimization_loop"), None
        )
        if optimization_artifact is not None:
            optimization_path = optimization_artifact.path(PROJECT_ROOT)
            if optimization_path.is_file():
                st.download_button(
                    "下载自动优化迭代 HTML",
                    data=optimization_path.read_bytes(),
                    file_name=optimization_path.name,
                    mime="text/html",
                )
                render_component(
                    read_rag_report(optimization_artifact, PROJECT_ROOT),
                    height=680,
                    scrolling=True,
                )

    if report is None:
        st.error("尚未找到失败分析报告。请先运行：uv run python scripts/analyze_rag_failures.py")
        return

    public = report.get("public", {})
    public = public if isinstance(public, dict) else {}
    public_metrics = public.get("metrics", {})
    public_metrics = public_metrics if isinstance(public_metrics, dict) else {}
    private = report.get("private_aggregate", {})
    private = private if isinstance(private, dict) else {}
    private_metrics = private.get("metrics", {})
    private_metrics = private_metrics if isinstance(private_metrics, dict) else {}
    private_counts = private.get("counts", {})
    private_counts = private_counts if isinstance(private_counts, dict) else {}
    errors = private.get("error_type_counts", {})
    errors = errors if isinstance(errors, dict) else {}

    st.subheader("当前评测事实")
    public_cards = st.columns(5)
    public_cards[0].metric("公开集 Route", _metric_value(public_metrics, "route_accuracy"))
    public_cards[1].metric("公开集 Recall@5", _metric_value(public_metrics, "recall_at_5"))
    public_cards[2].metric("固定 Precision@3", _metric_value(public_metrics, "precision_at_3"))
    public_cards[3].metric("隐藏集 Route（聚合）", _metric_value(private_metrics, "route_accuracy"))
    public_cards[4].metric("隐藏集错误题数", private_counts.get("error_case_count", "—"))

    st.info(
        "Precision 采用双口径并行报告：固定分母用于历史 Gate；覆盖式和返回式只用于解释 "
        "Gold 稀疏与额外噪声，不会自动替换项目门槛。"
    )
    st.dataframe(
        [
            {
                "指标": "固定 Precision@3",
                "含义": "命中数 / 3（历史可比）",
                "结果": _metric_value(public_metrics, "precision_at_3"),
            },
            {
                "指标": "覆盖式 Precision@3",
                "含义": "命中数 / min(3, Gold 条数)",
                "结果": _metric_value(public_metrics, "precision_at_3_effective"),
            },
            {
                "指标": "返回式 Precision@3",
                "含义": "命中数 / 实际返回条数（诊断）",
                "结果": _metric_value(public_metrics, "precision_at_3_returned"),
            },
        ],
        use_container_width=True,
        hide_index=True,
    )

    st.subheader("隐藏集错误类型（仅聚合）")
    if errors:
        st.bar_chart({"错误数": {str(key): int(value) for key, value in errors.items()}})
        st.dataframe(
            [{"错误类型": str(key), "数量": int(value)} for key, value in errors.items()],
            use_container_width=True,
            hide_index=True,
        )
    else:
        st.info("当前没有可展示的聚合错误类型。")

    st.subheader("公开集分层与指标口径")
    st.dataframe(_split_rows(public.get("groups")), use_container_width=True, hide_index=True)
    sparsity = public.get("sparsity", {})
    sparsity = sparsity if isinstance(sparsity, dict) else {}
    st.info(
        f"Gold 依据少于 3 条的公开题数：{sparsity.get('gold_evidence_fewer_than_3_cases', '—')}；"
        f"固定 Precision@3：{_percent(sparsity.get('fixed_precision_at_3_mean'))}；"
        f"按返回条数的诊断值：{_percent(sparsity.get('precision_at_returned_mean_diagnostic'))}；"
        f"安全事件未知标签：{public_metrics.get('safety_event_unknown_label_count', '—')}。"
        "诊断值用于解释稀疏分母，不替换当前冻结 Gate。"
    )

    st.subheader("Holdout 生命周期")
    st.warning(
        "v2 隐藏集只作为历史聚合诊断；Holdout A 已建立 v3 独立模板，待产品负责人在工作区外"
        "生成并保管题目/答案后，才能进行一次正式验收。"
    )

    st.subheader("Failure Pattern：为什么失败、准备怎样改")
    st.dataframe(_pattern_rows(report.get("patterns")), use_container_width=True, hide_index=True)

    correction = report.get("self_correction", {})
    correction = correction if isinstance(correction, dict) else {}
    candidate = correction.get("current_candidate", {})
    candidate = candidate if isinstance(candidate, dict) else {}
    candidate_regression = report.get("correction_candidate", {})
    candidate_regression = candidate_regression if isinstance(candidate_regression, dict) else {}
    trace_aggregate = candidate_regression.get("trace_aggregate", {})
    trace_aggregate = trace_aggregate if isinstance(trace_aggregate, dict) else {}
    st.subheader("自校正候选（人工批准前只提议）")
    status_cols = st.columns(4)
    status_cols[0].metric("候选状态", correction.get("status", "unknown"))
    status_cols[1].metric("公开回归", candidate_regression.get("regression_gate", "—"))
    status_cols[2].metric("归一化命中题数", trace_aggregate.get("normalization_applied_count", "—"))
    status_cols[3].metric("网络调用", "是" if trace_aggregate.get("network_called") else "否")
    st.write(f"候选：{candidate.get('name', '—')}")
    changes = candidate.get("changes", [])
    if isinstance(changes, list):
        for change in changes:
            st.write(f"- {change}")
    st.caption(f"回滚方式：{candidate.get('rollback', '—')}")
    blocked = correction.get("blocked_automatic_actions", [])
    if isinstance(blocked, list):
        st.write("自动化禁止项：" + "；".join(str(item) for item in blocked))

    st.subheader("可执行 SOP")
    st.dataframe(_sop_rows(report.get("sop")), use_container_width=True, hide_index=True)

    st.subheader("报告原件")
    failure_artifact = next(
        (item for item in RAG_REPORT_ARTIFACTS if item.key == "failure_analysis"), None
    )
    if failure_artifact is not None:
        failure_path = failure_artifact.path(PROJECT_ROOT)
        if failure_path.is_file():
            st.download_button(
                "下载失败分析 HTML",
                data=failure_path.read_bytes(),
                file_name=failure_path.name,
                mime="text/html",
            )
            render_component(
                read_rag_report(failure_artifact, PROJECT_ROOT), height=640, scrolling=True
            )


if __name__ == "__main__":
    main()
