"""Read-only local dashboard for RAG failure patterns and correction SOP.

The page reads one aggregate-only JSON artifact generated by
``scripts/analyze_rag_failures.py``.  It never opens a private answer key,
holdout input, photo, vector, trace, or network connection, and it cannot
apply the proposed correction automatically.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import streamlit as st
from streamlit.components.v1 import html as render_component

from portrait_consistency_agent.services.rag_report_registry import (
    RAG_REPORT_ARTIFACTS,
    read_rag_report,
)

PROJECT_ROOT = Path(__file__).resolve().parents[1]


def _load_json_report() -> dict[str, Any] | None:
    path = PROJECT_ROOT / "reports/rag_failure_patterns_v1.json"
    if not path.is_file():
        return None
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None
    return value if isinstance(value, dict) else None


def _load_optimization_report() -> dict[str, Any] | None:
    path = PROJECT_ROOT / "reports/rag_optimization_loop_v1.json"
    if not path.is_file():
        return None
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None
    return value if isinstance(value, dict) else None


def _load_failure_driven_report() -> dict[str, Any] | None:
    path = PROJECT_ROOT / "reports/rag_failure_driven_loop_v1.json"
    if not path.is_file():
        return None
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None
    return value if isinstance(value, dict) else None


def _load_v3_validation_report() -> dict[str, Any] | None:
    path = PROJECT_ROOT / "reports/rag_v3_validation_diagnostics_v1.json"
    if not path.is_file():
        return None
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None
    return value if isinstance(value, dict) else None


def _load_v4_validation_report() -> dict[str, Any] | None:
    path = PROJECT_ROOT / "reports/rag_v4_validation_diagnostics_v1.json"
    if not path.is_file():
        return None
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None
    return value if isinstance(value, dict) else None


def _load_v4_blind_aggregate() -> dict[str, Any] | None:
    path = PROJECT_ROOT / "reports/rag_v4_holdout_blind_aggregate.json"
    if not path.is_file():
        return None
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None
    return value if isinstance(value, dict) else None


def _load_fair_process_report() -> dict[str, Any] | None:
    path = PROJECT_ROOT / "reports/rag_fair_process_audit_v1.json"
    if not path.is_file():
        return None
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None
    return value if isinstance(value, dict) else None


def _load_fair_gold_join_report() -> dict[str, Any] | None:
    # v2 corrects the historical metric-scope bug; v1 remains a read-only
    # artifact for comparison and is never silently preferred.
    for path in (
        PROJECT_ROOT / "reports/rag_fair_gold_join_v2.json",
        PROJECT_ROOT / "reports/rag_fair_gold_join_v1.json",
    ):
        if not path.is_file():
            continue
        try:
            value = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            continue
        return value if isinstance(value, dict) else None
    return None


def _load_policy_coverage_candidate_report() -> dict[str, Any] | None:
    path = PROJECT_ROOT / "reports/rag_policy_coverage_candidate_v2.json"
    if not path.is_file():
        return None
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None
    return value if isinstance(value, dict) else None


def _load_candidate_diagnostics_report() -> dict[str, Any] | None:
    path = PROJECT_ROOT / "reports/rag_candidate_diagnostics_v1.json"
    if not path.is_file():
        return None
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None
    return value if isinstance(value, dict) else None


def _load_v5_process_audit_report() -> dict[str, Any] | None:
    path = PROJECT_ROOT / "reports/rag_v5_holdout_process_audit.json"
    if not path.is_file():
        return None
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None
    return value if isinstance(value, dict) else None


def _percent(value: object) -> str:
    if isinstance(value, (int, float)):
        return f"{float(value) * 100:.2f}%"
    return "—" if value is None else str(value)


def _metric_value(metrics: dict[str, Any], name: str) -> str:
    return _percent(metrics.get(name))


def _split_rows(groups: object) -> list[dict[str, object]]:
    if not isinstance(groups, dict):
        return []
    rows: list[dict[str, object]] = []
    for name, value in groups.items():
        if not isinstance(value, dict) or not str(name).startswith("split:"):
            continue
        rows.append(
            {
                "分组": str(name).removeprefix("split:"),
                "题数": value.get("cases", 0),
                "路由正确率": _percent(value.get("route_accuracy")),
                "关系正确率": _percent(value.get("evidence_relation_accuracy")),
                "固定 Precision@3": _percent(value.get("fixed_precision_at_3_mean")),
                "按返回条数诊断值": _percent(value.get("precision_at_returned_mean_diagnostic")),
            }
        )
    return rows


def _pattern_rows(patterns: object) -> list[dict[str, object]]:
    if not isinstance(patterns, list):
        return []
    return [
        {
            "模式": item.get("pattern_id", ""),
            "严重度": item.get("severity", ""),
            "证据级别": item.get("evidence_level", ""),
            "诊断": item.get("diagnosis", ""),
            "建议修正": item.get("correction", ""),
        }
        for item in patterns
        if isinstance(item, dict)
    ]


def _sop_rows(sop: object) -> list[dict[str, object]]:
    if not isinstance(sop, list):
        return []
    return [
        {
            "步骤": item.get("step", ""),
            "名称": item.get("name", ""),
            "执行": item.get("action", ""),
            "禁止": item.get("must_not", ""),
        }
        for item in sop
        if isinstance(item, dict)
    ]


def main() -> None:
    st.set_page_config(page_title="RAG 优化看板｜母版人像一致性 Agent", page_icon="🧪")
    report = _load_json_report()
    optimization = _load_optimization_report()
    failure_driven = _load_failure_driven_report()
    v3_validation = _load_v3_validation_report()
    v4_validation = _load_v4_validation_report()
    v4_blind = _load_v4_blind_aggregate()
    fair_process = _load_fair_process_report()
    fair_gold_join = _load_fair_gold_join_report()
    policy_candidate = _load_policy_coverage_candidate_report()
    candidate_diagnostics = _load_candidate_diagnostics_report()
    v5_process = _load_v5_process_audit_report()
    st.title("RAG 优化看板（本地管理员原型）")
    st.caption(
        "这张看板把公开集事实、隐藏集聚合错误和下一步修正 SOP 放在一起，帮助定位问题，"
        "但不会自动修改检索器、权限或 Provider。"
    )
    st.warning(
        "当前 RAG baseline 尚未通过项目 Gate。隐藏集只回流聚合统计；本页不读隐藏答案键、"
        "不展示隐藏题干/编号，也不把聚合结果当作逐题调参标签。"
    )
    if fair_process is not None:
        st.subheader("公平评测过程监督（独立考官）")
        st.caption(
            "先看考试是否完整、是否泄露答案或上游投影；只有过程门通过后，质量分数才有资格连接。"
        )
        process_cards = st.columns(5)
        process_cards[0].metric("新重放过程门", fair_process.get("fresh_replay_process_gate", "—"))
        process_cards[1].metric(
            "历史快照过程门", fair_process.get("historical_snapshot_process_gate", "—")
        )
        process_cards[2].metric("当前新运行过程门", fair_process.get("process_gate", "—"))
        process_cards[3].metric("新运行质量状态", fair_process.get("quality_scoring_gate", "—"))
        process_cards[4].metric(
            "历史质量状态", fair_process.get("historical_quality_scoring_gate", "—")
        )
        dataset_rows: list[dict[str, object]] = []
        datasets = fair_process.get("datasets", [])
        if isinstance(datasets, list):
            for dataset in datasets:
                if not isinstance(dataset, dict):
                    continue
                audit = dataset.get("audit", {})
                audit = audit if isinstance(audit, dict) else {}
                counts = audit.get("counts", {})
                counts = counts if isinstance(counts, dict) else {}
                dataset_rows.append(
                    {
                        "数据集": dataset.get("name", "—"),
                        "题目数": audit.get("case_count", 0),
                        "理解成功": counts.get("compiler_structured", 0),
                        "未知但继续检索": counts.get("compiler_unknown_fallback", 0),
                        "完整检索 Trace": counts.get("retrieval_complete", 0),
                        "过程失败": counts.get("case_fail", 0),
                        "过程门": audit.get("process_gate", "—"),
                    }
                )
        st.dataframe(dataset_rows, use_container_width=True, hide_index=True)
        historical = fair_process.get("historical_v4_snapshot", {})
        historical = historical if isinstance(historical, dict) else {}
        st.info(
            "新版重放通过后可进入独立 Gold 验证，但不改写旧正式考试；旧 V4 快照因缺阶段和投影注入，"
            "其历史质量状态继续锁定。"
            f"历史问题计数：{historical.get('violations_by_code', {}) or '无'}。"
        )
        fair_artifact = next(
            (item for item in RAG_REPORT_ARTIFACTS if item.key == "fair_process_audit"), None
        )
        if fair_artifact is not None:
            fair_path = fair_artifact.path(PROJECT_ROOT)
            if fair_path.is_file():
                st.download_button(
                    "下载公平过程审计 HTML",
                    data=fair_path.read_bytes(),
                    file_name=fair_path.name,
                    mime="text/html",
                    key="download_fair_process_audit_html",
                )
                render_component(
                    read_rag_report(fair_artifact, PROJECT_ROOT), height=560, scrolling=True
                )
        artifact_columns = st.columns(4)
        artifact_index = 0
        for dataset in datasets if isinstance(datasets, list) else []:
            if not isinstance(dataset, dict):
                continue
            artifacts = dataset.get("answerless_artifacts", {})
            if not isinstance(artifacts, dict):
                continue
            for artifact_kind in ("predictions", "trace"):
                raw_path = artifacts.get(artifact_kind)
                if not isinstance(raw_path, str):
                    continue
                artifact_path = Path(raw_path)
                if not artifact_path.is_file():
                    continue
                label = f"下载{dataset.get('name', '数据集')}脱敏{artifact_kind}"
                artifact_columns[artifact_index % len(artifact_columns)].download_button(
                    label,
                    data=artifact_path.read_bytes(),
                    file_name=artifact_path.name,
                    mime="application/json",
                    key=f"download_fair_{artifact_kind}_{artifact_index}",
                )
                artifact_index += 1
    if fair_gold_join is not None:
        st.subheader("公平 Gold 连接：自然语言理解与真实检索分轨")
        st.caption(
            "过程门通过后才允许一次性连接负责人 Gold；本区只展示聚合指标和失败类型，"
            "不显示题目、答案或私有路径。检索轨道只评证据，不把下游路由混入检索分数。"
        )
        join_cards = st.columns(3)
        join_cards[0].metric("质量连接状态", fair_gold_join.get("quality_scoring_gate", "—"))
        join_cards[1].metric("Promotion 状态", fair_gold_join.get("project_promotion_gate", "—"))
        join_cards[2].metric("下一步", fair_gold_join.get("next_step", "—"))
        join_rows: list[dict[str, object]] = []
        joined_datasets = fair_gold_join.get("datasets", [])
        for dataset in joined_datasets if isinstance(joined_datasets, list) else []:
            if not isinstance(dataset, dict):
                continue
            for track_key in ("compiler_track", "retrieval_track"):
                track = dataset.get(track_key, {})
                if not isinstance(track, dict):
                    continue
                metrics = track.get("metrics", {})
                metrics = metrics if isinstance(metrics, dict) else {}
                join_rows.append(
                    {
                        "数据集": dataset.get("name", "—"),
                        "轨道": track.get("track", track_key),
                        "题数": dataset.get("case_count", "—"),
                        "Route（编译轨道）": _percent(metrics.get("route_accuracy")),
                        "Recall@5": _percent(metrics.get("recall_at_5")),
                        "关系": _percent(metrics.get("evidence_relation_accuracy")),
                        "安全门": metrics.get("hard_safety_gate", "—"),
                        "失败类型": track.get("error_type_counts", {}),
                    }
                )
        st.dataframe(join_rows, use_container_width=True, hide_index=True)
        join_artifact = next(
            (item for item in RAG_REPORT_ARTIFACTS if item.key == "fair_gold_join"), None
        )
        if join_artifact is not None:
            join_path = join_artifact.path(PROJECT_ROOT)
            if join_path.is_file():
                st.download_button(
                    "下载公平 Gold 连接聚合 HTML",
                    data=join_path.read_bytes(),
                    file_name=join_path.name,
                    mime="text/html",
                    key="download_fair_gold_join_html",
                )
                render_component(
                    read_rag_report(join_artifact, PROJECT_ROOT), height=640, scrolling=True
                )
    if policy_candidate is not None:
        st.subheader("RAG 候选：检索能力与操作覆盖")
        st.caption(
            "这是公开开发/回归候选实验；它只比较真实检索结果，不改现役 baseline，"
            "也没有读取 Holdout 答案。"
        )
        candidate_rows: list[dict[str, object]] = []
        for dataset_name, dataset in (policy_candidate.get("datasets", {}) or {}).items():
            if not isinstance(dataset, dict):
                continue
            for track in ("retrieval_semantic_candidate", "retrieval_operation_coverage_candidate"):
                metrics = dataset.get(track, {})
                if not isinstance(metrics, dict):
                    continue
                candidate_rows.append(
                    {
                        "数据集": dataset_name,
                        "轨道": track.removeprefix("retrieval_"),
                        "题数": metrics.get("cases", "—"),
                        "关系": _percent(metrics.get("evidence_relation_accuracy")),
                        "Recall@5": _percent(metrics.get("recall_at_5")),
                        "MRR": _percent(metrics.get("mrr")),
                        "nDCG@5": _percent(metrics.get("ndcg_at_5")),
                    }
                )
        st.dataframe(candidate_rows, use_container_width=True, hide_index=True)
        st.write(
            "候选改变预测数（公开开发 / 回归）：",
            policy_candidate.get("changed_prediction_count", "—"),
            "/",
            policy_candidate.get("regression_changed_prediction_count", "—"),
        )
        st.info(
            "操作覆盖策略只重排已检索或已通过 active metadata 过滤的候选，"
            "不会制造证据、不会授予工具权限；正式推广仍需独立 V5 Holdout。"
        )
        candidate_artifact = next(
            (item for item in RAG_REPORT_ARTIFACTS if item.key == "policy_coverage_candidate"),
            None,
        )
        if candidate_artifact is not None and candidate_artifact.path(PROJECT_ROOT).is_file():
            render_component(
                read_rag_report(candidate_artifact, PROJECT_ROOT), height=600, scrolling=True
            )
    if candidate_diagnostics is not None:
        st.subheader("候选逐题失败模式")
        st.caption("逐题诊断只使用公开开发/回归答案，不包含 V3/V4/V5 私有答案。")
        st.write("根因计数：", candidate_diagnostics.get("aggregate_root_cause_counts", {}))
        st.write("候选轨道：", candidate_diagnostics.get("candidate_track", {}))
    if v5_process is not None:
        st.subheader("V5 独立 Holdout：过程监督状态")
        st.warning(
            "V5 已完成答案盲运行和过程门检查；质量分数必须在负责人审核答案键后，"
            "通过独立授权命令生成。"
        )
        v5_cards = st.columns(4)
        v5_cards[0].metric("题数", v5_process.get("case_count", "—"))
        v5_cards[1].metric("Trace 数", v5_process.get("trace_count", "—"))
        v5_cards[2].metric("过程门", v5_process.get("process_gate", "—"))
        v5_cards[3].metric("质量状态", v5_process.get("quality_scoring_gate", "—"))
        v5_artifact = next(
            (item for item in RAG_REPORT_ARTIFACTS if item.key == "v5_holdout_process_audit"),
            None,
        )
        if v5_artifact is not None and v5_artifact.path(PROJECT_ROOT).is_file():
            render_component(read_rag_report(v5_artifact, PROJECT_ROOT), height=360, scrolling=True)
    if failure_driven is not None:
        st.subheader("失败驱动迭代（查询理解层）")
        st.caption(
            "上一轮候选只改了已经生成的 Prediction；这一轮把修正放到"
            "‘自然语言→结构化 RAG 查询’之前。"
            "开发集标记为 owner_review_required，未替代正式 baseline。"
        )
        generations = failure_driven.get("generations", [])
        generations = generations if isinstance(generations, list) else []
        table: list[dict[str, object]] = []
        chart: list[dict[str, object]] = []
        for generation in generations:
            if not isinstance(generation, dict):
                continue
            metrics = generation.get("metrics", {})
            metrics = metrics if isinstance(metrics, dict) else {}
            table.append(
                {
                    "代次": generation.get("generation_id", "—"),
                    "候选": generation.get("version", "—"),
                    "实际改变预测数": generation.get("changed_prediction_count", "—"),
                    "Composite": generation.get("composite_score", "—"),
                    "增益": generation.get("composite_gain_vs_previous", "—"),
                    "Route": _percent(metrics.get("route_accuracy")),
                    "Relation": _percent(metrics.get("evidence_relation_accuracy")),
                    "Recall@5": _percent(metrics.get("recall_at_5")),
                    "公开回归 Gate": generation.get("regression_gate", "—"),
                }
            )
            if isinstance(generation.get("composite_score"), (int, float)):
                chart.append(
                    {
                        "代次": str(generation.get("generation_id", "—")),
                        "Composite": float(generation["composite_score"]),
                    }
                )
        st.dataframe(table, use_container_width=True, hide_index=True)
        if chart:
            st.line_chart(chart, x="代次", y="Composite")
        pattern_block = failure_driven.get("failure_patterns", {})
        pattern_block = pattern_block if isinstance(pattern_block, dict) else {}
        st.write("V0 失败模式：", pattern_block.get("baseline_failure_code_counts", {}))
        st.write("停止原因：", failure_driven.get("stop_reason", "—"))
        baseline_block = failure_driven.get("baseline", {})
        baseline_block = baseline_block if isinstance(baseline_block, dict) else {}
        failure_case_rows = baseline_block.get("case_diagnostics", [])
        failure_case_rows = failure_case_rows if isinstance(failure_case_rows, list) else []
        final_block = failure_driven.get("final_candidate_diagnostics", {})
        final_block = final_block if isinstance(final_block, dict) else {}
        final_case_rows = final_block.get("case_change_summary", [])
        final_case_rows = final_case_rows if isinstance(final_case_rows, list) else []
        with st.expander("查看失败驱动集逐题结论（不含 v3 私有答案）"):
            st.caption(
                "表格只显示本轮 owner-review 开发/挑战集的 case ID、标签、V0/终态错误码和路由变化。"
            )
            st.dataframe(
                final_case_rows or failure_case_rows, use_container_width=True, hide_index=True
            )
        st.write(
            "当前结论：",
            "查询编译候选在新开发集有明显增益；仍需产品负责人审核该数据集，"
            "并用独立 Holdout v4 验收。",
        )
        failure_artifact = next(
            (item for item in RAG_REPORT_ARTIFACTS if item.key == "failure_driven_loop"), None
        )
        if failure_artifact is not None:
            failure_path = failure_artifact.path(PROJECT_ROOT)
            if failure_path.is_file():
                st.download_button(
                    "下载失败驱动优化 HTML",
                    data=failure_path.read_bytes(),
                    file_name=failure_path.name,
                    mime="text/html",
                )
                render_component(
                    read_rag_report(failure_artifact, PROJECT_ROOT),
                    height=680,
                    scrolling=True,
                )
    if v3_validation is not None:
        st.subheader("V3 解冻验证集：逐题失败模式与 Trace")
        st.warning(
            "这是产品负责人明确解冻后的验证副本，不是独立 Holdout；原始一次性盲测快照仍保留。"
            "本区允许显示题干和逐题 Gold，仅供本机诊断，候选仍 proposal-only。"
        )
        v3_generations = v3_validation.get("generations", [])
        v3_generations = v3_generations if isinstance(v3_generations, list) else []
        v3_table: list[dict[str, object]] = []
        v3_chart: list[dict[str, object]] = []
        for generation in v3_generations:
            if not isinstance(generation, dict):
                continue
            metrics = generation.get("metrics", {})
            metrics = metrics if isinstance(metrics, dict) else {}
            v3_table.append(
                {
                    "代次": generation.get("generation_id", "—"),
                    "候选": generation.get("version", "—"),
                    "改变预测数": generation.get("changed_prediction_count", "—"),
                    "Composite": generation.get("composite_score", "—"),
                    "增益": generation.get("composite_gain_vs_previous", "—"),
                    "Route": _percent(metrics.get("route_accuracy")),
                    "Relation": _percent(metrics.get("evidence_relation_accuracy")),
                    "Recall@5": _percent(metrics.get("recall_at_5")),
                    "公开回归 Gate": generation.get("regression_gate", "—"),
                }
            )
            if isinstance(generation.get("composite_score"), (int, float)):
                v3_chart.append(
                    {
                        "代次": str(generation.get("generation_id", "—")),
                        "Composite": float(generation["composite_score"]),
                    }
                )
        st.dataframe(v3_table, use_container_width=True, hide_index=True)
        if v3_chart:
            st.line_chart(v3_chart, x="代次", y="Composite")
        st.write("G0 失败模式：", v3_validation.get("baseline_failure_counts", {}))
        st.write("最终失败模式：", v3_validation.get("final_failure_counts", {}))
        st.write("停止原因：", v3_validation.get("stop_reason", "—"))
        final_generation = v3_generations[-1] if v3_generations else {}
        final_cases = (
            final_generation.get("case_diagnostics", [])
            if isinstance(final_generation, dict)
            else []
        )
        final_cases = final_cases if isinstance(final_cases, list) else []
        with st.expander("查看 V3 逐题结论、根因与修正 SOP"):
            st.dataframe(
                [
                    {
                        "Case": row.get("case_id"),
                        "题目": row.get("query"),
                        "状态": row.get("status"),
                        "失败码": "、".join(str(item) for item in row.get("failure_codes", [])),
                        "根因": row.get("failure_analysis", {}).get("root_cause", "—"),
                        "修正": row.get("failure_analysis", {}).get("correction", "—"),
                    }
                    for row in final_cases
                    if isinstance(row, dict)
                ],
                use_container_width=True,
                hide_index=True,
            )
        v3_artifact = next(
            (item for item in RAG_REPORT_ARTIFACTS if item.key == "v3_validation_diagnostics"),
            None,
        )
        if v3_artifact is not None:
            v3_path = v3_artifact.path(PROJECT_ROOT)
            if v3_path.is_file():
                st.download_button(
                    "下载 V3 逐题诊断 HTML",
                    data=v3_path.read_bytes(),
                    file_name=v3_path.name,
                    mime="text/html",
                )
                render_component(
                    read_rag_report(v3_artifact, PROJECT_ROOT), height=720, scrolling=True
                )
    if v4_blind is not None or v4_validation is not None:
        st.subheader("V4 独立 Holdout：盲测与解冻诊断")
        st.warning(
            "V4 盲测先在不读答案的情况下封存；下面的逐题区是之后经负责人授权的验证副本。"
            "盲测成绩和诊断成绩分开显示，候选仍不改变正式 baseline。"
        )
        if v4_blind is not None:
            blind_metrics = v4_blind.get("metrics", {})
            blind_metrics = blind_metrics if isinstance(blind_metrics, dict) else {}
            blind_cards = st.columns(5)
            blind_cards[0].metric("盲测题数", v4_blind.get("case_count", "—"))
            blind_cards[1].metric("盲测 Route", _percent(blind_metrics.get("route_accuracy")))
            blind_cards[2].metric("盲测 Recall@5", _percent(blind_metrics.get("recall_at_5")))
            blind_cards[3].metric("盲测安全门", blind_metrics.get("hard_safety_gate", "—"))
            blind_cards[4].metric("盲测项目 Gate", blind_metrics.get("project_threshold_gate", "—"))
            st.caption("盲测聚合不含题目、案例编号、Gold 或答案键路径。")
        if v4_validation is not None:
            v4_generations = v4_validation.get("generations", [])
            v4_generations = v4_generations if isinstance(v4_generations, list) else []
            v4_table: list[dict[str, object]] = []
            v4_chart: list[dict[str, object]] = []
            for generation in v4_generations:
                if not isinstance(generation, dict):
                    continue
                metrics = generation.get("metrics", {})
                metrics = metrics if isinstance(metrics, dict) else {}
                v4_table.append(
                    {
                        "代次": generation.get("generation_id", "—"),
                        "候选": generation.get("version", "—"),
                        "改变预测数": generation.get("changed_prediction_count", "—"),
                        "Composite": generation.get("composite_score", "—"),
                        "Route": _percent(metrics.get("route_accuracy")),
                        "Relation": _percent(metrics.get("evidence_relation_accuracy")),
                        "有效 Recall@5": _percent(metrics.get("recall_at_5")),
                        "公开回归 Gate": generation.get("regression_gate", "—"),
                    }
                )
                if isinstance(generation.get("composite_score"), (int, float)):
                    v4_chart.append(
                        {
                            "代次": str(generation.get("generation_id", "—")),
                            "Composite": float(generation["composite_score"]),
                        }
                    )
            st.dataframe(v4_table, use_container_width=True, hide_index=True)
            if v4_chart:
                st.line_chart(v4_chart, x="代次", y="Composite")
            v4_improvement = v4_validation.get("improvement_summary", {})
            v4_improvement = v4_improvement if isinstance(v4_improvement, dict) else {}
            v4_cards = st.columns(3)
            v4_cards[0].metric("语义诊断门", v4_improvement.get("semantic_diagnostic_gate", "—"))
            v4_cards[1].metric("固定项目门", v4_improvement.get("frozen_project_gate", "—"))
            v4_cards[2].metric(
                "G0→最终改变题数", v4_improvement.get("changed_prediction_count_g0_to_final", "—")
            )
            st.write("V4 基线失败模式：", v4_validation.get("baseline_failure_counts", {}))
            st.write("V4 最终失败模式：", v4_validation.get("final_failure_counts", {}))
            st.write("停止原因：", v4_validation.get("stop_reason", "—"))
            final_generation = v4_generations[-1] if v4_generations else {}
            final_cases = (
                final_generation.get("case_diagnostics", [])
                if isinstance(final_generation, dict)
                else []
            )
            final_cases = final_cases if isinstance(final_cases, list) else []
            with st.expander("查看 V4 逐题结论、根因与修正 SOP"):
                st.dataframe(
                    [
                        {
                            "Case": row.get("case_id"),
                            "题目": row.get("query"),
                            "状态": row.get("status"),
                            "失败码": "、".join(str(item) for item in row.get("failure_codes", [])),
                            "根因": row.get("failure_analysis", {}).get("root_cause", "—"),
                            "修正": row.get("failure_analysis", {}).get("correction", "—"),
                        }
                        for row in final_cases
                        if isinstance(row, dict)
                    ],
                    use_container_width=True,
                    hide_index=True,
                )
            v4_artifact = next(
                (item for item in RAG_REPORT_ARTIFACTS if item.key == "v4_validation_diagnostics"),
                None,
            )
            if v4_artifact is not None:
                v4_path = v4_artifact.path(PROJECT_ROOT)
                if v4_path.is_file():
                    st.download_button(
                        "下载 V4 逐题诊断 HTML",
                        data=v4_path.read_bytes(),
                        file_name=v4_path.name,
                        mime="text/html",
                    )
                    render_component(
                        read_rag_report(v4_artifact, PROJECT_ROOT), height=720, scrolling=True
                    )
    if optimization is not None:
        st.subheader("版本化自动优化迭代")
        st.caption(
            "逐代只改一个可解释候选；Composite 仅作比较分，不能覆盖固定项目 Gate 或 hard-safety。"
        )
        generations = optimization.get("generations", [])
        generations = generations if isinstance(generations, list) else []
        generation_table: list[dict[str, object]] = []
        chart_rows: list[dict[str, object]] = []
        for generation in generations:
            if not isinstance(generation, dict):
                continue
            metrics = generation.get("metrics", {})
            metrics = metrics if isinstance(metrics, dict) else {}
            generation_table.append(
                {
                    "代次": generation.get("generation_id", "—"),
                    "候选版本": generation.get("version", "—"),
                    "状态": generation.get("status", "—"),
                    "Composite": generation.get("composite_score", "—"),
                    "增益": generation.get("composite_gain_vs_previous", "—"),
                    "Route": _percent(metrics.get("route_accuracy")),
                    "Recall@5": _percent(metrics.get("recall_at_5")),
                    "Project Gate": generation.get("project_threshold_gate", "—"),
                }
            )
            if isinstance(generation.get("composite_score"), (int, float)):
                chart_rows.append(
                    {
                        "代次": str(generation.get("generation_id", "—")),
                        "Composite": float(generation["composite_score"]),
                    }
                )
        st.dataframe(generation_table, use_container_width=True, hide_index=True)
        if chart_rows:
            st.line_chart(chart_rows, x="代次", y="Composite")
        anti_overfit = optimization.get("anti_overfit", {})
        anti_overfit = anti_overfit if isinstance(anti_overfit, dict) else {}
        status_cols = st.columns(3)
        executed_label = " → ".join(str(x) for x in optimization.get("executed_generations", []))
        status_cols[0].metric("执行代次", executed_label)
        status_cols[1].metric("反过拟合", anti_overfit.get("status", "—"))
        stop_label = (
            "边际效益递减" if "diminishing" in str(optimization.get("stop_reason")) else "计划完成"
        )
        status_cols[2].metric("停止原因", stop_label)
        public_patterns = optimization.get("failure_patterns", {})
        public_patterns = public_patterns if isinstance(public_patterns, dict) else {}
        case_diagnostics = optimization.get("baseline", {})
        case_diagnostics = case_diagnostics if isinstance(case_diagnostics, dict) else {}
        case_rows = case_diagnostics.get("case_diagnostics", [])
        case_rows = case_rows if isinstance(case_rows, list) else []
        st.write("公开集逐题模式计数：", public_patterns.get("public_case_pattern_counts", {}))
        with st.expander("查看公开集逐题诊断（不含原始题干）"):
            st.dataframe(case_rows, use_container_width=True, hide_index=True)
        interpretations = public_patterns.get("private_pattern_interpretations", [])
        if isinstance(interpretations, list) and interpretations:
            st.subheader("v3 聚合模式：事实与假设分开")
            interpretation_rows = []
            for item in interpretations:
                if not isinstance(item, dict):
                    continue
                causes = item.get("plausible_causes", [])
                if not isinstance(causes, list):
                    causes = []
                interpretation_rows.append(
                    {
                        "模式": item.get("pattern_id", "—"),
                        "计数": item.get("count", 0),
                        "证据级别": item.get("evidence_level", "—"),
                        "观察事实": item.get("what_is_observed", "—"),
                        "可验证假设": "；".join(str(cause) for cause in causes),
                        "下一份 Holdout 要补的证据": item.get("next_evidence_needed", "—"),
                    }
                )
            st.dataframe(interpretation_rows, use_container_width=True, hide_index=True)
            st.caption("v3 模式计数可能重叠；假设不等于隐藏集逐题答案，需在独立 Holdout v4 验证。")
        optimization_artifact = next(
            (item for item in RAG_REPORT_ARTIFACTS if item.key == "optimization_loop"), None
        )
        if optimization_artifact is not None:
            optimization_path = optimization_artifact.path(PROJECT_ROOT)
            if optimization_path.is_file():
                st.download_button(
                    "下载自动优化迭代 HTML",
                    data=optimization_path.read_bytes(),
                    file_name=optimization_path.name,
                    mime="text/html",
                )
                render_component(
                    read_rag_report(optimization_artifact, PROJECT_ROOT),
                    height=680,
                    scrolling=True,
                )

    if report is None:
        if fair_process is None:
            st.error(
                "尚未找到失败分析报告。请先运行：uv run python scripts/analyze_rag_failures.py"
            )
        else:
            st.info("当前只有公平过程审计报告；失败模式汇总报告尚未生成。")
        return

    public = report.get("public", {})
    public = public if isinstance(public, dict) else {}
    public_metrics = public.get("metrics", {})
    public_metrics = public_metrics if isinstance(public_metrics, dict) else {}
    private = report.get("private_aggregate", {})
    private = private if isinstance(private, dict) else {}
    private_metrics = private.get("metrics", {})
    private_metrics = private_metrics if isinstance(private_metrics, dict) else {}
    private_counts = private.get("counts", {})
    private_counts = private_counts if isinstance(private_counts, dict) else {}
    errors = private.get("error_type_counts", {})
    errors = errors if isinstance(errors, dict) else {}

    st.subheader("当前评测事实")
    public_cards = st.columns(5)
    public_cards[0].metric("公开集 Route", _metric_value(public_metrics, "route_accuracy"))
    public_cards[1].metric("公开集 Recall@5", _metric_value(public_metrics, "recall_at_5"))
    public_cards[2].metric("固定 Precision@3", _metric_value(public_metrics, "precision_at_3"))
    public_cards[3].metric("隐藏集 Route（聚合）", _metric_value(private_metrics, "route_accuracy"))
    public_cards[4].metric("隐藏集错误题数", private_counts.get("error_case_count", "—"))

    st.info(
        "Precision 采用双口径并行报告：固定分母用于历史 Gate；覆盖式和返回式只用于解释 "
        "Gold 稀疏与额外噪声，不会自动替换项目门槛。"
    )
    st.dataframe(
        [
            {
                "指标": "固定 Precision@3",
                "含义": "命中数 / 3（历史可比）",
                "结果": _metric_value(public_metrics, "precision_at_3"),
            },
            {
                "指标": "覆盖式 Precision@3",
                "含义": "命中数 / min(3, Gold 条数)",
                "结果": _metric_value(public_metrics, "precision_at_3_effective"),
            },
            {
                "指标": "返回式 Precision@3",
                "含义": "命中数 / 实际返回条数（诊断）",
                "结果": _metric_value(public_metrics, "precision_at_3_returned"),
            },
        ],
        use_container_width=True,
        hide_index=True,
    )

    st.subheader("隐藏集错误类型（仅聚合）")
    if errors:
        st.bar_chart({"错误数": {str(key): int(value) for key, value in errors.items()}})
        st.dataframe(
            [{"错误类型": str(key), "数量": int(value)} for key, value in errors.items()],
            use_container_width=True,
            hide_index=True,
        )
    else:
        st.info("当前没有可展示的聚合错误类型。")

    st.subheader("公开集分层与指标口径")
    st.dataframe(_split_rows(public.get("groups")), use_container_width=True, hide_index=True)
    sparsity = public.get("sparsity", {})
    sparsity = sparsity if isinstance(sparsity, dict) else {}
    st.info(
        f"Gold 依据少于 3 条的公开题数：{sparsity.get('gold_evidence_fewer_than_3_cases', '—')}；"
        f"固定 Precision@3：{_percent(sparsity.get('fixed_precision_at_3_mean'))}；"
        f"按返回条数的诊断值：{_percent(sparsity.get('precision_at_returned_mean_diagnostic'))}；"
        f"安全事件未知标签：{public_metrics.get('safety_event_unknown_label_count', '—')}。"
        "诊断值用于解释稀疏分母，不替换当前冻结 Gate。"
    )

    st.subheader("Holdout 生命周期")
    st.warning(
        "v2 隐藏集只作为历史聚合诊断；Holdout A 已建立 v3 独立模板，待产品负责人在工作区外"
        "生成并保管题目/答案后，才能进行一次正式验收。"
    )

    st.subheader("Failure Pattern：为什么失败、准备怎样改")
    st.dataframe(_pattern_rows(report.get("patterns")), use_container_width=True, hide_index=True)

    correction = report.get("self_correction", {})
    correction = correction if isinstance(correction, dict) else {}
    candidate = correction.get("current_candidate", {})
    candidate = candidate if isinstance(candidate, dict) else {}
    candidate_regression = report.get("correction_candidate", {})
    candidate_regression = candidate_regression if isinstance(candidate_regression, dict) else {}
    trace_aggregate = candidate_regression.get("trace_aggregate", {})
    trace_aggregate = trace_aggregate if isinstance(trace_aggregate, dict) else {}
    st.subheader("自校正候选（人工批准前只提议）")
    status_cols = st.columns(4)
    status_cols[0].metric("候选状态", correction.get("status", "unknown"))
    status_cols[1].metric("公开回归", candidate_regression.get("regression_gate", "—"))
    status_cols[2].metric("归一化命中题数", trace_aggregate.get("normalization_applied_count", "—"))
    status_cols[3].metric("网络调用", "是" if trace_aggregate.get("network_called") else "否")
    st.write(f"候选：{candidate.get('name', '—')}")
    changes = candidate.get("changes", [])
    if isinstance(changes, list):
        for change in changes:
            st.write(f"- {change}")
    st.caption(f"回滚方式：{candidate.get('rollback', '—')}")
    blocked = correction.get("blocked_automatic_actions", [])
    if isinstance(blocked, list):
        st.write("自动化禁止项：" + "；".join(str(item) for item in blocked))

    st.subheader("可执行 SOP")
    st.dataframe(_sop_rows(report.get("sop")), use_container_width=True, hide_index=True)

    st.subheader("报告原件")
    failure_artifact = next(
        (item for item in RAG_REPORT_ARTIFACTS if item.key == "failure_analysis"), None
    )
    if failure_artifact is not None:
        failure_path = failure_artifact.path(PROJECT_ROOT)
        if failure_path.is_file():
            st.download_button(
                "下载失败分析 HTML",
                data=failure_path.read_bytes(),
                file_name=failure_path.name,
                mime="text/html",
            )
            render_component(
                read_rag_report(failure_artifact, PROJECT_ROOT), height=640, scrolling=True
            )


if __name__ == "__main__":
    main()
