"""Read-only E3 evidence dashboard for the Tencent Effect Web candidate.

The page only reads the redacted report generated by
``scripts/build_effect_web_e3_evidence.py``.  It never loads credentials,
opens the SDK or promotes a Provider Card.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import streamlit as st

PROJECT_ROOT = Path(__file__).resolve().parents[1]
REPORT_PATH = PROJECT_ROOT / "reports/effect_web_e3_evidence_v1.json"


def _load_report() -> dict[str, Any] | None:
    if not REPORT_PATH.is_file():
        return None
    try:
        value = json.loads(REPORT_PATH.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None
    return value if isinstance(value, dict) else None


def main() -> None:
    st.set_page_config(page_title="腾讯特效 Web E3 证据看板", page_icon="🧾")
    st.title("腾讯特效 Web｜E3 真实证据看板")
    st.caption(
        "这张看板把真实浏览器回执、样本哈希绑定、结果交接和合同回归放在一起；"
        "它不会把 SDK 成功当作视觉一致性泛化，也不会自动升级 candidate。"
    )
    report = _load_report()
    if report is None:
        st.info("尚未生成 E3 证据报告；运行 build_effect_web_e3_evidence.py 后刷新。")
        return

    live = report.get("live_summary", {})
    if not isinstance(live, dict):
        live = {}
    offline = report.get("offline_contract_regression", {})
    if not isinstance(offline, dict):
        offline = {}
    metrics = st.columns(6)
    metrics[0].metric("真实回执", f"{live.get('succeeded', 0)}/{live.get('total_receipts', 0)}")
    metrics[1].metric("成功率", f"{float(live.get('success_rate', 0)):.0%}")
    metrics[2].metric(
        "输入哈希绑定",
        "PASS" if live.get("sample_hashes_match_preflight") else "FAIL",
    )
    metrics[3].metric("结果交接", live.get("handoff_accepted", 0))
    metrics[4].metric(
        "合同回归",
        "PASS" if offline.get("passed") else "FAIL",
    )
    metrics[5].metric("Card 状态", report.get("promotion_status", "candidate"))

    if report.get("visual_generalization_status") == "not_established":
        st.warning(
            "视觉效果泛化仍未建立：当前证据证明图片被 SDK 处理并返回结果，不证明结果已经更像母版。"
        )
    st.info("结果图、data URL 和本地路径均未写入报告；哈希仅用于样本与回执的证据关联。")

    st.subheader("真实回执明细")
    receipts = report.get("receipts", [])
    if isinstance(receipts, list):
        rows = [
            {
                "样本": item.get("sample_id"),
                "Receipt": item.get("receipt_id"),
                "状态": item.get("status"),
                "耗时(ms)": item.get("elapsed_ms"),
                "输入哈希已绑定": "是" if item.get("input_sha256") else "否",
                "结果交接": "是" if item.get("handoff_accepted") else "否",
                "request_ref 已记录": "是" if item.get("request_ref_recorded") else "否",
                "复测状态": item.get("verification_status"),
            }
            for item in receipts
            if isinstance(item, dict)
        ]
        st.dataframe(rows, use_container_width=True, hide_index=True)

    st.subheader("尚未闭合的准入 Gate")
    blockers = report.get("blockers", [])
    if isinstance(blockers, list):
        for blocker in blockers:
            st.write(f"• {blocker}")

    st.subheader("下一步")
    actions = report.get("next_actions", [])
    if isinstance(actions, list):
        for action in actions:
            st.write(f"• {action}")

    st.download_button(
        "下载脱敏 E3 JSON",
        data=REPORT_PATH.read_bytes(),
        file_name=REPORT_PATH.name,
        mime="application/json",
    )


if __name__ == "__main__":
    main()
