#!/usr/bin/env python3
"""Score holdout predictions locally with a product-owner supplied private key.

This script is intentionally not part of normal development or CI.  It has no
default answer key.  The product owner must explicitly pass a private local
path with ``--private-answer-key``; the key is used only in memory and its path
is never printed or written to the aggregate result.

The only output is aggregate metrics and error-type counts.  It never emits
case IDs, questions, Gold routes/evidence, raw user text, photos, vectors,
secrets, or provider data.  It makes no network/LLM/Provider call.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from portrait_consistency_agent.services.rag_gold_eval import (
    GoldSetFormatError,
    evaluate,
    load_annotations,
    load_holdout_runtime_cases,
    load_predictions,
)
from portrait_consistency_agent.services.rag_gold_private_score import (
    parse_private_markdown_annotations,
    private_aggregate_payload,
    render_private_aggregate_html,
)

PROJECT_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_HOLDOUT_RUNTIME = PROJECT_ROOT / "data/evaluation/rag_gold_v2_holdout_runtime.json"


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--holdout-runtime",
        type=Path,
        default=DEFAULT_HOLDOUT_RUNTIME,
        help="Answerless H* runtime package only.",
    )
    parser.add_argument(
        "--predictions",
        type=Path,
        required=True,
        help="Redacted H* prediction package generated by the baseline runner.",
    )
    parser.add_argument(
        "--private-answer-key",
        type=Path,
        required=True,
        help="Product-owner-only local path; it is never printed or persisted by this script.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        required=True,
        help="Aggregate-only JSON output path on the product owner's machine.",
    )
    parser.add_argument(
        "--html-output",
        type=Path,
        help="Optional aggregate-only HTML report; never contains case-level or Gold data.",
    )
    return parser


def _write_json(path: Path, payload: object) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def _load_private_annotations(
    path: Path, *, allowed_case_ids: tuple[str, ...]
) -> tuple[object, str]:
    """Read a PM private key only in memory; Markdown never leaves this process."""

    if path.suffix.casefold() == ".md":
        return (
            parse_private_markdown_annotations(
                path.read_text(encoding="utf-8"), allowed_case_ids=allowed_case_ids
            ),
            "markdown_table_v1",
        )
    return (
        load_annotations(path, allowed_case_ids=allowed_case_ids),
        "machine_normalized_json",
    )


def main() -> int:
    args = _parser().parse_args()
    try:
        dataset_version, cases = load_holdout_runtime_cases(args.holdout_runtime)
        predictions = load_predictions(args.predictions)
        annotations, annotation_source = _load_private_annotations(
            args.private_answer_key,
            allowed_case_ids=tuple(case.case_id for case in cases),
        )
        report = evaluate(
            cases=cases,
            annotations=annotations,
            predictions=predictions,
            dataset_version=dataset_version,
        )
    except GoldSetFormatError:
        # Do not echo a product-owner private path in a terminal/log capture.
        print("Private holdout scoring input was rejected; no aggregate output was written.")
        return 2

    payload = private_aggregate_payload(report, annotation_source=annotation_source)
    _write_json(args.output, payload)
    if args.html_output is not None:
        args.html_output.parent.mkdir(parents=True, exist_ok=True)
        args.html_output.write_text(render_private_aggregate_html(payload), encoding="utf-8")
    print(
        json.dumps(
            {
                "status": payload["status"],
                "scope": payload["scope"],
                "aggregate_output_written": True,
                "aggregate_html_written": args.html_output is not None,
                "case_ids_emitted": False,
                "questions_emitted": False,
                "answer_facts_emitted": False,
                "private_answer_key_path_emitted": False,
                "llm_called": False,
                "photo_or_face_vector_read": False,
                "external_provider_called": False,
                "network_called": False,
            },
            ensure_ascii=False,
            indent=2,
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
